name: Build and Deploy to Cloud Run (all branches)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Show gcloud version and configuration
        run: |-
          gcloud version
          gcloud config list

      - name: Build and Push Docker image
        run: |-
          export GCP_PROJECT=${{ secrets.GCP_PROJECT }}
          export GCP_APPLICATION=${{ secrets.GCP_APPLICATION }}
          export IMAGE_TAG=$GITHUB_SHA
          envsubst < cloudbuild.yaml > cloudbuild_deployed.yaml
          gcloud builds submit --quiet --config cloudbuild_deployed.yaml

      - name: Deploy to Cloud Run
        run: |-
          export GCP_PROJECT=${{ secrets.GCP_PROJECT }}
          export GCP_APPLICATION=${{ secrets.GCP_APPLICATION }}
          export IMAGE_TAG=$GITHUB_SHA
          export ENVIRONMENT_TEST=${{ secrets.ENVIRONMENT_TEST }}
          envsubst < services.yml > services_deployed.yml
          gcloud run services replace services_deployed.yml --region us-central1

      - name: Add IAM policy binding
        run: |-
          gcloud run services add-iam-policy-binding ${{ secrets.GCP_APPLICATION }} \
            --region us-central1 \
            --member="allUsers" \
            --role="roles/run.invoker"
